"""Generate SQL Server DDL + load scripts from fub_api.schema.

Writes three files into sql/:
  create_tables.sql      typed final tables in schema [fub]
  staging_tables.sql     all-NVARCHAR staging tables in schema [stg]
  load_bulk_insert.sql   BULK INSERT csv -> stg, then TRY_CONVERT cast -> fub

Load pattern (why staging):
  Our CSVs encode NULL as empty string and BIT as '1'/'0' (DATA_RULES). A
  direct BULK INSERT into a typed table chokes on '' for INT/DATE/BIT. So we
  land raw text in [stg].* then INSERT..SELECT with TRY_CONVERT(type, NULLIF(
  col,'')) — '' becomes NULL, bad values become NULL instead of failing the
  whole load. TRY_CONVERT failures can then be audited in SQL.

Run:
  .venv/bin/python scripts/generate_ddl.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from fub_api.schema import SCHEMAS, base_type, validate  # noqa: E402

SQL_DIR = ROOT / "sql"


def _cast_expr(col: str, sql_type: str) -> str:
    """SQL expression to convert a staging text column to its typed value."""
    bt = base_type(sql_type)
    src = f"NULLIF([{col}], '')"
    if bt in ("VARCHAR", "NVARCHAR", "CHAR", "NCHAR"):
        return src
    return f"TRY_CONVERT({sql_type}, {src})"


def gen_create_tables() -> str:
    out = [
        "-- Generated by scripts/generate_ddl.py — do not edit by hand.",
        "-- Typed final tables. Matches the CSV column order exactly.",
        "IF SCHEMA_ID('fub') IS NULL EXEC('CREATE SCHEMA fub');",
        "GO",
        "",
    ]
    for table, (columns, types, pk) in SCHEMAS.items():
        out.append(f"IF OBJECT_ID('fub.{table}', 'U') IS NOT NULL DROP TABLE fub.{table};")
        out.append("GO")
        out.append(f"CREATE TABLE fub.{table} (")
        lines = []
        for c in columns:
            nullable = "NOT NULL" if c == pk else "NULL"
            lines.append(f"    [{c}] {types[c]} {nullable}")
        out.append(",\n".join(lines))
        out.append(f"    , CONSTRAINT PK_fub_{table} PRIMARY KEY ([{pk}])")
        out.append(");")
        out.append("GO")
        out.append("")
    return "\n".join(out)


def gen_staging_tables() -> str:
    out = [
        "-- Generated by scripts/generate_ddl.py — do not edit by hand.",
        "-- Staging tables: every column NVARCHAR(MAX) so BULK INSERT never",
        "-- fails on type. Cast happens in load_bulk_insert.sql.",
        "IF SCHEMA_ID('stg') IS NULL EXEC('CREATE SCHEMA stg');",
        "GO",
        "",
    ]
    for table, (columns, _types, _pk) in SCHEMAS.items():
        out.append(f"IF OBJECT_ID('stg.{table}', 'U') IS NOT NULL DROP TABLE stg.{table};")
        out.append("GO")
        out.append(f"CREATE TABLE stg.{table} (")
        lines = [f"    [{c}] NVARCHAR(MAX) NULL" for c in columns]
        out.append(",\n".join(lines))
        out.append(");")
        out.append("GO")
        out.append("")
    return "\n".join(out)


def gen_load() -> str:
    out = [
        "-- Generated by scripts/generate_ddl.py — do not edit by hand.",
        "-- Requires SQL Server 2017+ (FORMAT='CSV'). Run with sqlcmd and set",
        "-- the data directory the SQL Server service account can read:",
        "--   sqlcmd -S host -d db -v DataDir=\"C:\\fub\\exports\" -i load_bulk_insert.sql",
        ":setvar DataDir \"REPLACE_WITH_EXPORT_DIR\"",
        "GO",
        "",
    ]
    for table, (columns, types, _pk) in SCHEMAS.items():
        out.append(f"-- ===== {table} =====")
        out.append(f"TRUNCATE TABLE stg.{table};")
        out.append("GO")
        out.append(f"BULK INSERT stg.{table}")
        out.append(f"FROM '$(DataDir)\\{table}.csv'")
        out.append("WITH (")
        out.append("    FORMAT = 'CSV',")
        out.append("    FIRSTROW = 2,            -- skip header (also skips the BOM line)")
        out.append("    FIELDTERMINATOR = ',',")
        out.append("    ROWTERMINATOR = '0x0d0a',-- CRLF; if last col keeps a trailing CR, use '0x0a'")
        out.append("    FIELDQUOTE = '\"',")
        out.append("    CODEPAGE = '65001',      -- UTF-8")
        out.append("    TABLOCK")
        out.append(");")
        out.append("GO")
        out.append(f"INSERT INTO fub.{table} (")
        out.append("    " + ",\n    ".join(f"[{c}]" for c in columns))
        out.append(")")
        out.append("SELECT")
        out.append("    " + ",\n    ".join(f"{_cast_expr(c, types[c])} AS [{c}]" for c in columns))
        out.append(f"FROM stg.{table};")
        out.append("GO")
        out.append("")
    out.append("-- Reconcile against data/exports/manifest.json:")
    for table in SCHEMAS:
        out.append(f"SELECT '{table}' AS TableName, COUNT(*) AS Rows FROM fub.{table};")
    out.append("GO")
    return "\n".join(out)


def main() -> None:
    validate()
    SQL_DIR.mkdir(exist_ok=True)
    (SQL_DIR / "create_tables.sql").write_text(gen_create_tables(), encoding="utf-8")
    (SQL_DIR / "staging_tables.sql").write_text(gen_staging_tables(), encoding="utf-8")
    (SQL_DIR / "load_bulk_insert.sql").write_text(gen_load(), encoding="utf-8")
    print("Wrote sql/create_tables.sql, sql/staging_tables.sql, sql/load_bulk_insert.sql")
    for table, (columns, _t, pk) in SCHEMAS.items():
        print(f"  fub.{table}: {len(columns)} columns, PK={pk}")


if __name__ == "__main__":
    main()
