"""Generate PostgreSQL DDL for the fub.* tables from fub_api.schema.

The Postgres counterpart to scripts/generate_ddl.py. `fub_api.schema.SCHEMAS`
stays the single source of truth for columns/order/types/PK — this script only
swaps the *dialect*:

  * SQL Server types  -> Postgres types   (see PG_TYPE / pg_type)
  * [Bracket] quoting -> "double-quote" quoting (preserves PascalCase; Postgres
    folds unquoted identifiers to lowercase — see DB_MIGRATION.md §4.1)
  * IF SCHEMA_ID/OBJECT_ID guards + GO  ->  CREATE SCHEMA IF NOT EXISTS /
    DROP TABLE IF EXISTS, statements separated by ';' (no GO; apply via psql -f)

There is NO staging layer: the psycopg loader (postgres/load_to_pg.py) loads
typed values directly, so the all-NVARCHAR stg.* tables that BULK INSERT needed
are not generated for Postgres.

Run:
    .venv/bin/python postgres/generate_pg_ddl.py
    psql "$PG_URL" -f postgres/sql/create_tables.sql      # apply on the VPS
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from fub_api.schema import SCHEMAS, base_type, validate  # noqa: E402

OUT_DIR = Path(__file__).resolve().parent / "sql"

# SQL Server base type -> a function of its (length/precision) arg -> PG type.
PG_TYPE = {
    "NVARCHAR": lambda a: "TEXT" if a.upper() == "MAX" else f"VARCHAR({a})",
    "VARCHAR": lambda a: f"VARCHAR({a})",
    "INT": lambda _a: "INTEGER",
    "BIGINT": lambda _a: "BIGINT",
    "BIT": lambda _a: "BOOLEAN",
    "DATE": lambda _a: "DATE",
    "DATETIME2": lambda _a: "TIMESTAMP(3)",
}


def pg_type(sql_type: str) -> str:
    """'NVARCHAR(256)' -> 'VARCHAR(256)', 'NVARCHAR(MAX)' -> 'TEXT', etc."""
    bt = base_type(sql_type)
    arg = sql_type[sql_type.find("(") + 1: sql_type.rfind(")")] if "(" in sql_type else ""
    if bt not in PG_TYPE:
        raise ValueError(f"No Postgres mapping for SQL type {sql_type!r}")
    return PG_TYPE[bt](arg)


def gen_create_tables() -> str:
    out = [
        "-- Generated by postgres/generate_pg_ddl.py — do not edit by hand.",
        "-- PostgreSQL DDL for the typed fub.* tables. Column order matches the CSVs.",
        "-- Identifiers are double-quoted to preserve PascalCase (DB_MIGRATION.md §4.1).",
        "",
        "CREATE SCHEMA IF NOT EXISTS fub;",
        "",
    ]
    for table, (columns, types, pk) in SCHEMAS.items():
        out.append(f'DROP TABLE IF EXISTS fub."{table}" CASCADE;')
        out.append(f'CREATE TABLE fub."{table}" (')
        lines = []
        for c in columns:
            null = " NOT NULL" if c == pk else ""
            lines.append(f'    "{c}" {pg_type(types[c])}{null}')
        lines.append(f'    CONSTRAINT "PK_fub_{table}" PRIMARY KEY ("{pk}")')
        out.append(",\n".join(lines))
        out.append(");")
        out.append("")
    return "\n".join(out)


def main() -> None:
    validate()  # mapper columns <-> typed columns must stay in sync (hard error)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / "create_tables.sql"
    path.write_text(gen_create_tables(), encoding="utf-8")
    print(f"Wrote {path.relative_to(ROOT)}")
    for table, (columns, _t, pk) in SCHEMAS.items():
        print(f"  fub.{table}: {len(columns)} columns, PK={pk}")


if __name__ == "__main__":
    main()
