-- Generated by scripts/generate_ddl.py — do not edit by hand.
-- Typed final tables. Matches the CSV column order exactly.
IF SCHEMA_ID('fub') IS NULL EXEC('CREATE SCHEMA fub');
GO

IF OBJECT_ID('fub.People', 'U') IS NOT NULL DROP TABLE fub.People;
GO
CREATE TABLE fub.People (
    [PersonId] VARCHAR(64) NOT NULL,
    [Name] NVARCHAR(256) NULL,
    [FirstName] NVARCHAR(128) NULL,
    [LastName] NVARCHAR(128) NULL,
    [Stage] NVARCHAR(128) NULL,
    [StageId] INT NULL,
    [Type] NVARCHAR(64) NULL,
    [Source] NVARCHAR(128) NULL,
    [SourceId] INT NULL,
    [LeadFlowId] INT NULL,
    [AssignedUserId] INT NULL,
    [AssignedTo] NVARCHAR(128) NULL,
    [AssignedLenderId] INT NULL,
    [AssignedLenderName] NVARCHAR(128) NULL,
    [AssignedPondId] INT NULL,
    [PrimaryEmail] NVARCHAR(256) NULL,
    [PrimaryPhone] VARCHAR(32) NULL,
    [Emails] NVARCHAR(1024) NULL,
    [Phones] NVARCHAR(512) NULL,
    [Tags] NVARCHAR(2048) NULL,
    [AddressStreet] NVARCHAR(256) NULL,
    [AddressCity] NVARCHAR(128) NULL,
    [AddressState] NVARCHAR(64) NULL,
    [AddressCode] NVARCHAR(32) NULL,
    [Price] BIGINT NULL,
    [IsDelayed] BIT NULL,
    [ContactedCount] INT NULL,
    [IsClaimed] BIT NULL,
    [WebsiteVisits] INT NULL,
    [DealStatus] NVARCHAR(64) NULL,
    [DealStage] NVARCHAR(128) NULL,
    [DealName] NVARCHAR(256) NULL,
    [DealCloseDate] DATE NULL,
    [DealPrice] BIGINT NULL,
    [CreatedVia] NVARCHAR(64) NULL,
    [CreatedUtc] DATETIME2(3) NULL,
    [UpdatedUtc] DATETIME2(3) NULL,
    [LastActivityUtc] DATETIME2(3) NULL,
    [CustomBirthday] DATE NULL,
    [CustomClosingAnniversary] DATE NULL,
    [CustomColdCaller] NVARCHAR(512) NULL,
    [CustomDateOfSale] DATE NULL,
    [CustomEstimatedAvailableEquity] NVARCHAR(512) NULL,
    [CustomEstimatedEquity] NVARCHAR(512) NULL,
    [CustomEstimatedLoanBalance] NVARCHAR(512) NULL,
    [CustomHomeownerDeceased] NVARCHAR(512) NULL,
    [CustomInterestRate] NVARCHAR(512) NULL,
    [CustomLTVRatio] NVARCHAR(512) NULL,
    [CustomLease] NVARCHAR(512) NULL,
    [CustomLeaseExpiry] NVARCHAR(512) NULL,
    [CustomLengthOfOwnership] NVARCHAR(512) NULL,
    [CustomMonthlyRent] NVARCHAR(512) NULL,
    [CustomMortgageAmount] NVARCHAR(512) NULL,
    [CustomMortgagee] NVARCHAR(512) NULL,
    [CustomOccupancy] NVARCHAR(512) NULL,
    [CustomPropertiesAtMailingAddress] NVARCHAR(512) NULL,
    [CustomPropertyCondition] NVARCHAR(512) NULL,
    [CustomSRan] NVARCHAR(512) NULL,
    [CustomSellerSIdealPrice] NVARCHAR(512) NULL,
    [CustomWebsite] NVARCHAR(512) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [SourceSystem] VARCHAR(32) NULL,
    [SourceSystemId] VARCHAR(64) NULL,
    [ExtractedAtUtc] DATETIME2(3) NULL
    , CONSTRAINT PK_fub_People PRIMARY KEY ([PersonId])
);
GO

IF OBJECT_ID('fub.Deals', 'U') IS NOT NULL DROP TABLE fub.Deals;
GO
CREATE TABLE fub.Deals (
    [DealId] VARCHAR(64) NOT NULL,
    [Name] NVARCHAR(512) NULL,
    [DealType] INT NULL,
    [Status] NVARCHAR(64) NULL,
    [Price] BIGINT NULL,
    [OrderWeight] INT NULL,
    [Description] NVARCHAR(4000) NULL,
    [PipelineId] INT NULL,
    [PipelineName] NVARCHAR(256) NULL,
    [StageId] INT NULL,
    [StageName] NVARCHAR(256) NULL,
    [EnteredStageUtc] DATETIME2(3) NULL,
    [CommissionValue] BIGINT NULL,
    [AgentCommission] BIGINT NULL,
    [TeamCommission] BIGINT NULL,
    [TimeToClose] INT NULL,
    [ProjectedCloseDate] DATE NULL,
    [EarnestMoneyDueDate] DATE NULL,
    [MutualAcceptanceDate] DATE NULL,
    [DueDiligenceDate] DATE NULL,
    [FinalWalkThroughDate] DATE NULL,
    [PossessionDate] DATE NULL,
    [CustomClosingDate] DATE NULL,
    [PrimaryPersonId] VARCHAR(64) NULL,
    [PersonIds] NVARCHAR(512) NULL,
    [PersonNames] NVARCHAR(1024) NULL,
    [PrimaryUserId] VARCHAR(64) NULL,
    [UserIds] NVARCHAR(256) NULL,
    [UserNames] NVARCHAR(512) NULL,
    [CreatedUtc] DATETIME2(3) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [SourceSystem] VARCHAR(32) NULL,
    [SourceSystemId] VARCHAR(64) NULL,
    [ExtractedAtUtc] DATETIME2(3) NULL
    , CONSTRAINT PK_fub_Deals PRIMARY KEY ([DealId])
);
GO

IF OBJECT_ID('fub.Events', 'U') IS NOT NULL DROP TABLE fub.Events;
GO
CREATE TABLE fub.Events (
    [EventId] VARCHAR(64) NOT NULL,
    [PersonId] VARCHAR(64) NULL,
    [Type] NVARCHAR(128) NULL,
    [Source] NVARCHAR(128) NULL,
    [Message] NVARCHAR(4000) NULL,
    [Description] NVARCHAR(4000) NULL,
    [NoteId] VARCHAR(64) NULL,
    [PageTitle] NVARCHAR(512) NULL,
    [PageUrl] NVARCHAR(1024) NULL,
    [PageDuration] INT NULL,
    [Property] NVARCHAR(4000) NULL,
    [PropertySearch] NVARCHAR(4000) NULL,
    [Additional] NVARCHAR(4000) NULL,
    [OccurredUtc] DATETIME2(3) NULL,
    [CreatedUtc] DATETIME2(3) NULL,
    [UpdatedUtc] DATETIME2(3) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [SourceSystem] VARCHAR(32) NULL,
    [SourceSystemId] VARCHAR(64) NULL,
    [ExtractedAtUtc] DATETIME2(3) NULL
    , CONSTRAINT PK_fub_Events PRIMARY KEY ([EventId])
);
GO

IF OBJECT_ID('fub.Tasks', 'U') IS NOT NULL DROP TABLE fub.Tasks;
GO
CREATE TABLE fub.Tasks (
    [TaskId] VARCHAR(64) NOT NULL,
    [PersonId] VARCHAR(64) NULL,
    [Name] NVARCHAR(512) NULL,
    [Type] NVARCHAR(128) NULL,
    [IsCompleted] BIT NULL,
    [CompletedUtc] DATETIME2(3) NULL,
    [DueDate] DATE NULL,
    [DueDateTimeUtc] DATETIME2(3) NULL,
    [AssignedUserId] INT NULL,
    [AssignedTo] NVARCHAR(128) NULL,
    [CreatedById] INT NULL,
    [CreatedBy] NVARCHAR(128) NULL,
    [UpdatedById] INT NULL,
    [UpdatedBy] NVARCHAR(128) NULL,
    [RemindSecondsBefore] INT NULL,
    [ExternalCalendarId] NVARCHAR(128) NULL,
    [ExternalTaskLink] NVARCHAR(1024) NULL,
    [CreatedUtc] DATETIME2(3) NULL,
    [UpdatedUtc] DATETIME2(3) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [SourceSystem] VARCHAR(32) NULL,
    [SourceSystemId] VARCHAR(64) NULL,
    [ExtractedAtUtc] DATETIME2(3) NULL
    , CONSTRAINT PK_fub_Tasks PRIMARY KEY ([TaskId])
);
GO

IF OBJECT_ID('fub.Notes', 'U') IS NOT NULL DROP TABLE fub.Notes;
GO
CREATE TABLE fub.Notes (
    [NoteId] VARCHAR(64) NOT NULL,
    [PersonId] VARCHAR(64) NULL,
    [Subject] NVARCHAR(512) NULL,
    [Body] NVARCHAR(MAX) NULL,
    [Type] NVARCHAR(64) NULL,
    [IsHtml] BIT NULL,
    [IsExternal] BIT NULL,
    [SystemName] NVARCHAR(128) NULL,
    [CreatedById] INT NULL,
    [CreatedBy] NVARCHAR(128) NULL,
    [UpdatedById] INT NULL,
    [UpdatedBy] NVARCHAR(128) NULL,
    [CreatedUtc] DATETIME2(3) NULL,
    [UpdatedUtc] DATETIME2(3) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [SourceSystem] VARCHAR(32) NULL,
    [SourceSystemId] VARCHAR(64) NULL,
    [ExtractedAtUtc] DATETIME2(3) NULL
    , CONSTRAINT PK_fub_Notes PRIMARY KEY ([NoteId])
);
GO

IF OBJECT_ID('fub.Calls', 'U') IS NOT NULL DROP TABLE fub.Calls;
GO
CREATE TABLE fub.Calls (
    [CallId] VARCHAR(64) NOT NULL,
    [PersonId] VARCHAR(64) NULL,
    [UserId] INT NULL,
    [UserName] NVARCHAR(128) NULL,
    [IsIncoming] BIT NULL,
    [Duration] INT NULL,
    [RingDuration] INT NULL,
    [Outcome] NVARCHAR(128) NULL,
    [Note] NVARCHAR(4000) NULL,
    [Phone] VARCHAR(32) NULL,
    [FromNumber] VARCHAR(32) NULL,
    [ToNumber] VARCHAR(32) NULL,
    [Name] NVARCHAR(256) NULL,
    [FirstName] NVARCHAR(128) NULL,
    [LastName] NVARCHAR(128) NULL,
    [RecordingUrl] NVARCHAR(1024) NULL,
    [CreatedById] INT NULL,
    [StartedAtUtc] DATETIME2(3) NULL,
    [CreatedUtc] DATETIME2(3) NULL,
    [UpdatedUtc] DATETIME2(3) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [SourceSystem] VARCHAR(32) NULL,
    [SourceSystemId] VARCHAR(64) NULL,
    [ExtractedAtUtc] DATETIME2(3) NULL
    , CONSTRAINT PK_fub_Calls PRIMARY KEY ([CallId])
);
GO

IF OBJECT_ID('fub.Users', 'U') IS NOT NULL DROP TABLE fub.Users;
GO
CREATE TABLE fub.Users (
    [UserId] VARCHAR(64) NOT NULL,
    [Name] NVARCHAR(256) NULL,
    [FirstName] NVARCHAR(128) NULL,
    [LastName] NVARCHAR(128) NULL,
    [Email] NVARCHAR(256) NULL,
    [Phone] VARCHAR(32) NULL,
    [Role] NVARCHAR(64) NULL,
    [Status] NVARCHAR(64) NULL,
    [Timezone] NVARCHAR(64) NULL,
    [IsOwner] BIT NULL,
    [PauseLeadDistribution] BIT NULL,
    [CanExport] BIT NULL,
    [CanCreateApiKeys] BIT NULL,
    [Fuid] VARCHAR(64) NULL,
    [LeadEmailAddress] NVARCHAR(256) NULL,
    [PictureUrl] NVARCHAR(1024) NULL,
    [GroupIds] NVARCHAR(256) NULL,
    [GroupNames] NVARCHAR(1024) NULL,
    [LastSeenIosUtc] DATETIME2(3) NULL,
    [LastSeenAndroidUtc] DATETIME2(3) NULL,
    [LastSeenFub2Utc] DATETIME2(3) NULL,
    [CreatedUtc] DATETIME2(3) NULL,
    [UpdatedUtc] DATETIME2(3) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [SourceSystem] VARCHAR(32) NULL,
    [SourceSystemId] VARCHAR(64) NULL,
    [ExtractedAtUtc] DATETIME2(3) NULL
    , CONSTRAINT PK_fub_Users PRIMARY KEY ([UserId])
);
GO

IF OBJECT_ID('fub.Pipelines', 'U') IS NOT NULL DROP TABLE fub.Pipelines;
GO
CREATE TABLE fub.Pipelines (
    [PipelineId] VARCHAR(64) NOT NULL,
    [Name] NVARCHAR(256) NULL,
    [Description] NVARCHAR(1024) NULL,
    [OrderWeight] INT NULL,
    [StageCount] INT NULL,
    [StageIds] NVARCHAR(512) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [SourceSystem] VARCHAR(32) NULL,
    [SourceSystemId] VARCHAR(64) NULL,
    [ExtractedAtUtc] DATETIME2(3) NULL
    , CONSTRAINT PK_fub_Pipelines PRIMARY KEY ([PipelineId])
);
GO

IF OBJECT_ID('fub.Stages', 'U') IS NOT NULL DROP TABLE fub.Stages;
GO
CREATE TABLE fub.Stages (
    [StageId] VARCHAR(64) NOT NULL,
    [Name] NVARCHAR(256) NULL,
    [PipelineId] INT NULL,
    [StageKind] VARCHAR(16) NULL,
    [OrderWeight] INT NULL,
    [IsProtected] BIT NULL,
    [PeopleCount] INT NULL,
    [Color] VARCHAR(32) NULL,
    [ClosedStage] BIT NULL,
    [Description] NVARCHAR(1024) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [SourceSystem] VARCHAR(32) NULL,
    [SourceSystemId] VARCHAR(64) NULL,
    [ExtractedAtUtc] DATETIME2(3) NULL
    , CONSTRAINT PK_fub_Stages PRIMARY KEY ([StageId])
);
GO

IF OBJECT_ID('fub.Sources', 'U') IS NOT NULL DROP TABLE fub.Sources;
GO
CREATE TABLE fub.Sources (
    [SourceId] INT NOT NULL,
    [Name] NVARCHAR(128) NULL,
    [PeopleCount] INT NULL,
    [Derived] BIT NULL,
    [SourceSystem] VARCHAR(32) NULL,
    [SourceSystemId] VARCHAR(64) NULL,
    [ExtractedAtUtc] DATETIME2(3) NULL
    , CONSTRAINT PK_fub_Sources PRIMARY KEY ([SourceId])
);
GO

IF OBJECT_ID('fub.Tags', 'U') IS NOT NULL DROP TABLE fub.Tags;
GO
CREATE TABLE fub.Tags (
    [TagName] NVARCHAR(256) NOT NULL,
    [PeopleCount] INT NULL,
    [Derived] BIT NULL,
    [SourceSystem] VARCHAR(32) NULL,
    [SourceSystemId] NVARCHAR(256) NULL,
    [ExtractedAtUtc] DATETIME2(3) NULL
    , CONSTRAINT PK_fub_Tags PRIMARY KEY ([TagName])
);
GO
