-- Generated by scripts/generate_ddl.py — do not edit by hand.
-- Requires SQL Server 2017+ (FORMAT='CSV'). Run with sqlcmd and set
-- the data directory the SQL Server service account can read:
--   sqlcmd -S host -d db -v DataDir="C:\fub\exports" -i load_bulk_insert.sql
:setvar DataDir "REPLACE_WITH_EXPORT_DIR"
GO

-- ===== People =====
TRUNCATE TABLE stg.People;
GO
BULK INSERT stg.People
FROM '$(DataDir)\People.csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,            -- skip header (also skips the BOM line)
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0d0a',-- CRLF; if last col keeps a trailing CR, use '0x0a'
    FIELDQUOTE = '"',
    CODEPAGE = '65001',      -- UTF-8
    TABLOCK
);
GO
INSERT INTO fub.People (
    [PersonId],
    [Name],
    [FirstName],
    [LastName],
    [Stage],
    [StageId],
    [Type],
    [Source],
    [SourceId],
    [LeadFlowId],
    [AssignedUserId],
    [AssignedTo],
    [AssignedLenderId],
    [AssignedLenderName],
    [AssignedPondId],
    [PrimaryEmail],
    [PrimaryPhone],
    [Emails],
    [Phones],
    [Tags],
    [AddressStreet],
    [AddressCity],
    [AddressState],
    [AddressCode],
    [Price],
    [IsDelayed],
    [ContactedCount],
    [IsClaimed],
    [WebsiteVisits],
    [DealStatus],
    [DealStage],
    [DealName],
    [DealCloseDate],
    [DealPrice],
    [CreatedVia],
    [CreatedUtc],
    [UpdatedUtc],
    [LastActivityUtc],
    [CustomBirthday],
    [CustomClosingAnniversary],
    [CustomColdCaller],
    [CustomDateOfSale],
    [CustomEstimatedAvailableEquity],
    [CustomEstimatedEquity],
    [CustomEstimatedLoanBalance],
    [CustomHomeownerDeceased],
    [CustomInterestRate],
    [CustomLTVRatio],
    [CustomLease],
    [CustomLeaseExpiry],
    [CustomLengthOfOwnership],
    [CustomMonthlyRent],
    [CustomMortgageAmount],
    [CustomMortgagee],
    [CustomOccupancy],
    [CustomPropertiesAtMailingAddress],
    [CustomPropertyCondition],
    [CustomSRan],
    [CustomSellerSIdealPrice],
    [CustomWebsite],
    [RawJson],
    [SourceSystem],
    [SourceSystemId],
    [ExtractedAtUtc]
)
SELECT
    NULLIF([PersonId], '') AS [PersonId],
    NULLIF([Name], '') AS [Name],
    NULLIF([FirstName], '') AS [FirstName],
    NULLIF([LastName], '') AS [LastName],
    NULLIF([Stage], '') AS [Stage],
    TRY_CONVERT(INT, NULLIF([StageId], '')) AS [StageId],
    NULLIF([Type], '') AS [Type],
    NULLIF([Source], '') AS [Source],
    TRY_CONVERT(INT, NULLIF([SourceId], '')) AS [SourceId],
    TRY_CONVERT(INT, NULLIF([LeadFlowId], '')) AS [LeadFlowId],
    TRY_CONVERT(INT, NULLIF([AssignedUserId], '')) AS [AssignedUserId],
    NULLIF([AssignedTo], '') AS [AssignedTo],
    TRY_CONVERT(INT, NULLIF([AssignedLenderId], '')) AS [AssignedLenderId],
    NULLIF([AssignedLenderName], '') AS [AssignedLenderName],
    TRY_CONVERT(INT, NULLIF([AssignedPondId], '')) AS [AssignedPondId],
    NULLIF([PrimaryEmail], '') AS [PrimaryEmail],
    NULLIF([PrimaryPhone], '') AS [PrimaryPhone],
    NULLIF([Emails], '') AS [Emails],
    NULLIF([Phones], '') AS [Phones],
    NULLIF([Tags], '') AS [Tags],
    NULLIF([AddressStreet], '') AS [AddressStreet],
    NULLIF([AddressCity], '') AS [AddressCity],
    NULLIF([AddressState], '') AS [AddressState],
    NULLIF([AddressCode], '') AS [AddressCode],
    TRY_CONVERT(BIGINT, NULLIF([Price], '')) AS [Price],
    TRY_CONVERT(BIT, NULLIF([IsDelayed], '')) AS [IsDelayed],
    TRY_CONVERT(INT, NULLIF([ContactedCount], '')) AS [ContactedCount],
    TRY_CONVERT(BIT, NULLIF([IsClaimed], '')) AS [IsClaimed],
    TRY_CONVERT(INT, NULLIF([WebsiteVisits], '')) AS [WebsiteVisits],
    NULLIF([DealStatus], '') AS [DealStatus],
    NULLIF([DealStage], '') AS [DealStage],
    NULLIF([DealName], '') AS [DealName],
    TRY_CONVERT(DATE, NULLIF([DealCloseDate], '')) AS [DealCloseDate],
    TRY_CONVERT(BIGINT, NULLIF([DealPrice], '')) AS [DealPrice],
    NULLIF([CreatedVia], '') AS [CreatedVia],
    TRY_CONVERT(DATETIME2(3), NULLIF([CreatedUtc], '')) AS [CreatedUtc],
    TRY_CONVERT(DATETIME2(3), NULLIF([UpdatedUtc], '')) AS [UpdatedUtc],
    TRY_CONVERT(DATETIME2(3), NULLIF([LastActivityUtc], '')) AS [LastActivityUtc],
    TRY_CONVERT(DATE, NULLIF([CustomBirthday], '')) AS [CustomBirthday],
    TRY_CONVERT(DATE, NULLIF([CustomClosingAnniversary], '')) AS [CustomClosingAnniversary],
    NULLIF([CustomColdCaller], '') AS [CustomColdCaller],
    TRY_CONVERT(DATE, NULLIF([CustomDateOfSale], '')) AS [CustomDateOfSale],
    NULLIF([CustomEstimatedAvailableEquity], '') AS [CustomEstimatedAvailableEquity],
    NULLIF([CustomEstimatedEquity], '') AS [CustomEstimatedEquity],
    NULLIF([CustomEstimatedLoanBalance], '') AS [CustomEstimatedLoanBalance],
    NULLIF([CustomHomeownerDeceased], '') AS [CustomHomeownerDeceased],
    NULLIF([CustomInterestRate], '') AS [CustomInterestRate],
    NULLIF([CustomLTVRatio], '') AS [CustomLTVRatio],
    NULLIF([CustomLease], '') AS [CustomLease],
    NULLIF([CustomLeaseExpiry], '') AS [CustomLeaseExpiry],
    NULLIF([CustomLengthOfOwnership], '') AS [CustomLengthOfOwnership],
    NULLIF([CustomMonthlyRent], '') AS [CustomMonthlyRent],
    NULLIF([CustomMortgageAmount], '') AS [CustomMortgageAmount],
    NULLIF([CustomMortgagee], '') AS [CustomMortgagee],
    NULLIF([CustomOccupancy], '') AS [CustomOccupancy],
    NULLIF([CustomPropertiesAtMailingAddress], '') AS [CustomPropertiesAtMailingAddress],
    NULLIF([CustomPropertyCondition], '') AS [CustomPropertyCondition],
    NULLIF([CustomSRan], '') AS [CustomSRan],
    NULLIF([CustomSellerSIdealPrice], '') AS [CustomSellerSIdealPrice],
    NULLIF([CustomWebsite], '') AS [CustomWebsite],
    NULLIF([RawJson], '') AS [RawJson],
    NULLIF([SourceSystem], '') AS [SourceSystem],
    NULLIF([SourceSystemId], '') AS [SourceSystemId],
    TRY_CONVERT(DATETIME2(3), NULLIF([ExtractedAtUtc], '')) AS [ExtractedAtUtc]
FROM stg.People;
GO

-- ===== Deals =====
TRUNCATE TABLE stg.Deals;
GO
BULK INSERT stg.Deals
FROM '$(DataDir)\Deals.csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,            -- skip header (also skips the BOM line)
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0d0a',-- CRLF; if last col keeps a trailing CR, use '0x0a'
    FIELDQUOTE = '"',
    CODEPAGE = '65001',      -- UTF-8
    TABLOCK
);
GO
INSERT INTO fub.Deals (
    [DealId],
    [Name],
    [DealType],
    [Status],
    [Price],
    [OrderWeight],
    [Description],
    [PipelineId],
    [PipelineName],
    [StageId],
    [StageName],
    [EnteredStageUtc],
    [CommissionValue],
    [AgentCommission],
    [TeamCommission],
    [TimeToClose],
    [ProjectedCloseDate],
    [EarnestMoneyDueDate],
    [MutualAcceptanceDate],
    [DueDiligenceDate],
    [FinalWalkThroughDate],
    [PossessionDate],
    [CustomClosingDate],
    [PrimaryPersonId],
    [PersonIds],
    [PersonNames],
    [PrimaryUserId],
    [UserIds],
    [UserNames],
    [CreatedUtc],
    [RawJson],
    [SourceSystem],
    [SourceSystemId],
    [ExtractedAtUtc]
)
SELECT
    NULLIF([DealId], '') AS [DealId],
    NULLIF([Name], '') AS [Name],
    TRY_CONVERT(INT, NULLIF([DealType], '')) AS [DealType],
    NULLIF([Status], '') AS [Status],
    TRY_CONVERT(BIGINT, NULLIF([Price], '')) AS [Price],
    TRY_CONVERT(INT, NULLIF([OrderWeight], '')) AS [OrderWeight],
    NULLIF([Description], '') AS [Description],
    TRY_CONVERT(INT, NULLIF([PipelineId], '')) AS [PipelineId],
    NULLIF([PipelineName], '') AS [PipelineName],
    TRY_CONVERT(INT, NULLIF([StageId], '')) AS [StageId],
    NULLIF([StageName], '') AS [StageName],
    TRY_CONVERT(DATETIME2(3), NULLIF([EnteredStageUtc], '')) AS [EnteredStageUtc],
    TRY_CONVERT(BIGINT, NULLIF([CommissionValue], '')) AS [CommissionValue],
    TRY_CONVERT(BIGINT, NULLIF([AgentCommission], '')) AS [AgentCommission],
    TRY_CONVERT(BIGINT, NULLIF([TeamCommission], '')) AS [TeamCommission],
    TRY_CONVERT(INT, NULLIF([TimeToClose], '')) AS [TimeToClose],
    TRY_CONVERT(DATE, NULLIF([ProjectedCloseDate], '')) AS [ProjectedCloseDate],
    TRY_CONVERT(DATE, NULLIF([EarnestMoneyDueDate], '')) AS [EarnestMoneyDueDate],
    TRY_CONVERT(DATE, NULLIF([MutualAcceptanceDate], '')) AS [MutualAcceptanceDate],
    TRY_CONVERT(DATE, NULLIF([DueDiligenceDate], '')) AS [DueDiligenceDate],
    TRY_CONVERT(DATE, NULLIF([FinalWalkThroughDate], '')) AS [FinalWalkThroughDate],
    TRY_CONVERT(DATE, NULLIF([PossessionDate], '')) AS [PossessionDate],
    TRY_CONVERT(DATE, NULLIF([CustomClosingDate], '')) AS [CustomClosingDate],
    NULLIF([PrimaryPersonId], '') AS [PrimaryPersonId],
    NULLIF([PersonIds], '') AS [PersonIds],
    NULLIF([PersonNames], '') AS [PersonNames],
    NULLIF([PrimaryUserId], '') AS [PrimaryUserId],
    NULLIF([UserIds], '') AS [UserIds],
    NULLIF([UserNames], '') AS [UserNames],
    TRY_CONVERT(DATETIME2(3), NULLIF([CreatedUtc], '')) AS [CreatedUtc],
    NULLIF([RawJson], '') AS [RawJson],
    NULLIF([SourceSystem], '') AS [SourceSystem],
    NULLIF([SourceSystemId], '') AS [SourceSystemId],
    TRY_CONVERT(DATETIME2(3), NULLIF([ExtractedAtUtc], '')) AS [ExtractedAtUtc]
FROM stg.Deals;
GO

-- ===== Events =====
TRUNCATE TABLE stg.Events;
GO
BULK INSERT stg.Events
FROM '$(DataDir)\Events.csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,            -- skip header (also skips the BOM line)
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0d0a',-- CRLF; if last col keeps a trailing CR, use '0x0a'
    FIELDQUOTE = '"',
    CODEPAGE = '65001',      -- UTF-8
    TABLOCK
);
GO
INSERT INTO fub.Events (
    [EventId],
    [PersonId],
    [Type],
    [Source],
    [Message],
    [Description],
    [NoteId],
    [PageTitle],
    [PageUrl],
    [PageDuration],
    [Property],
    [PropertySearch],
    [Additional],
    [OccurredUtc],
    [CreatedUtc],
    [UpdatedUtc],
    [RawJson],
    [SourceSystem],
    [SourceSystemId],
    [ExtractedAtUtc]
)
SELECT
    NULLIF([EventId], '') AS [EventId],
    NULLIF([PersonId], '') AS [PersonId],
    NULLIF([Type], '') AS [Type],
    NULLIF([Source], '') AS [Source],
    NULLIF([Message], '') AS [Message],
    NULLIF([Description], '') AS [Description],
    NULLIF([NoteId], '') AS [NoteId],
    NULLIF([PageTitle], '') AS [PageTitle],
    NULLIF([PageUrl], '') AS [PageUrl],
    TRY_CONVERT(INT, NULLIF([PageDuration], '')) AS [PageDuration],
    NULLIF([Property], '') AS [Property],
    NULLIF([PropertySearch], '') AS [PropertySearch],
    NULLIF([Additional], '') AS [Additional],
    TRY_CONVERT(DATETIME2(3), NULLIF([OccurredUtc], '')) AS [OccurredUtc],
    TRY_CONVERT(DATETIME2(3), NULLIF([CreatedUtc], '')) AS [CreatedUtc],
    TRY_CONVERT(DATETIME2(3), NULLIF([UpdatedUtc], '')) AS [UpdatedUtc],
    NULLIF([RawJson], '') AS [RawJson],
    NULLIF([SourceSystem], '') AS [SourceSystem],
    NULLIF([SourceSystemId], '') AS [SourceSystemId],
    TRY_CONVERT(DATETIME2(3), NULLIF([ExtractedAtUtc], '')) AS [ExtractedAtUtc]
FROM stg.Events;
GO

-- ===== Tasks =====
TRUNCATE TABLE stg.Tasks;
GO
BULK INSERT stg.Tasks
FROM '$(DataDir)\Tasks.csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,            -- skip header (also skips the BOM line)
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0d0a',-- CRLF; if last col keeps a trailing CR, use '0x0a'
    FIELDQUOTE = '"',
    CODEPAGE = '65001',      -- UTF-8
    TABLOCK
);
GO
INSERT INTO fub.Tasks (
    [TaskId],
    [PersonId],
    [Name],
    [Type],
    [IsCompleted],
    [CompletedUtc],
    [DueDate],
    [DueDateTimeUtc],
    [AssignedUserId],
    [AssignedTo],
    [CreatedById],
    [CreatedBy],
    [UpdatedById],
    [UpdatedBy],
    [RemindSecondsBefore],
    [ExternalCalendarId],
    [ExternalTaskLink],
    [CreatedUtc],
    [UpdatedUtc],
    [RawJson],
    [SourceSystem],
    [SourceSystemId],
    [ExtractedAtUtc]
)
SELECT
    NULLIF([TaskId], '') AS [TaskId],
    NULLIF([PersonId], '') AS [PersonId],
    NULLIF([Name], '') AS [Name],
    NULLIF([Type], '') AS [Type],
    TRY_CONVERT(BIT, NULLIF([IsCompleted], '')) AS [IsCompleted],
    TRY_CONVERT(DATETIME2(3), NULLIF([CompletedUtc], '')) AS [CompletedUtc],
    TRY_CONVERT(DATE, NULLIF([DueDate], '')) AS [DueDate],
    TRY_CONVERT(DATETIME2(3), NULLIF([DueDateTimeUtc], '')) AS [DueDateTimeUtc],
    TRY_CONVERT(INT, NULLIF([AssignedUserId], '')) AS [AssignedUserId],
    NULLIF([AssignedTo], '') AS [AssignedTo],
    TRY_CONVERT(INT, NULLIF([CreatedById], '')) AS [CreatedById],
    NULLIF([CreatedBy], '') AS [CreatedBy],
    TRY_CONVERT(INT, NULLIF([UpdatedById], '')) AS [UpdatedById],
    NULLIF([UpdatedBy], '') AS [UpdatedBy],
    TRY_CONVERT(INT, NULLIF([RemindSecondsBefore], '')) AS [RemindSecondsBefore],
    NULLIF([ExternalCalendarId], '') AS [ExternalCalendarId],
    NULLIF([ExternalTaskLink], '') AS [ExternalTaskLink],
    TRY_CONVERT(DATETIME2(3), NULLIF([CreatedUtc], '')) AS [CreatedUtc],
    TRY_CONVERT(DATETIME2(3), NULLIF([UpdatedUtc], '')) AS [UpdatedUtc],
    NULLIF([RawJson], '') AS [RawJson],
    NULLIF([SourceSystem], '') AS [SourceSystem],
    NULLIF([SourceSystemId], '') AS [SourceSystemId],
    TRY_CONVERT(DATETIME2(3), NULLIF([ExtractedAtUtc], '')) AS [ExtractedAtUtc]
FROM stg.Tasks;
GO

-- ===== Notes =====
TRUNCATE TABLE stg.Notes;
GO
BULK INSERT stg.Notes
FROM '$(DataDir)\Notes.csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,            -- skip header (also skips the BOM line)
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0d0a',-- CRLF; if last col keeps a trailing CR, use '0x0a'
    FIELDQUOTE = '"',
    CODEPAGE = '65001',      -- UTF-8
    TABLOCK
);
GO
INSERT INTO fub.Notes (
    [NoteId],
    [PersonId],
    [Subject],
    [Body],
    [Type],
    [IsHtml],
    [IsExternal],
    [SystemName],
    [CreatedById],
    [CreatedBy],
    [UpdatedById],
    [UpdatedBy],
    [CreatedUtc],
    [UpdatedUtc],
    [RawJson],
    [SourceSystem],
    [SourceSystemId],
    [ExtractedAtUtc]
)
SELECT
    NULLIF([NoteId], '') AS [NoteId],
    NULLIF([PersonId], '') AS [PersonId],
    NULLIF([Subject], '') AS [Subject],
    NULLIF([Body], '') AS [Body],
    NULLIF([Type], '') AS [Type],
    TRY_CONVERT(BIT, NULLIF([IsHtml], '')) AS [IsHtml],
    TRY_CONVERT(BIT, NULLIF([IsExternal], '')) AS [IsExternal],
    NULLIF([SystemName], '') AS [SystemName],
    TRY_CONVERT(INT, NULLIF([CreatedById], '')) AS [CreatedById],
    NULLIF([CreatedBy], '') AS [CreatedBy],
    TRY_CONVERT(INT, NULLIF([UpdatedById], '')) AS [UpdatedById],
    NULLIF([UpdatedBy], '') AS [UpdatedBy],
    TRY_CONVERT(DATETIME2(3), NULLIF([CreatedUtc], '')) AS [CreatedUtc],
    TRY_CONVERT(DATETIME2(3), NULLIF([UpdatedUtc], '')) AS [UpdatedUtc],
    NULLIF([RawJson], '') AS [RawJson],
    NULLIF([SourceSystem], '') AS [SourceSystem],
    NULLIF([SourceSystemId], '') AS [SourceSystemId],
    TRY_CONVERT(DATETIME2(3), NULLIF([ExtractedAtUtc], '')) AS [ExtractedAtUtc]
FROM stg.Notes;
GO

-- ===== Calls =====
TRUNCATE TABLE stg.Calls;
GO
BULK INSERT stg.Calls
FROM '$(DataDir)\Calls.csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,            -- skip header (also skips the BOM line)
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0d0a',-- CRLF; if last col keeps a trailing CR, use '0x0a'
    FIELDQUOTE = '"',
    CODEPAGE = '65001',      -- UTF-8
    TABLOCK
);
GO
INSERT INTO fub.Calls (
    [CallId],
    [PersonId],
    [UserId],
    [UserName],
    [IsIncoming],
    [Duration],
    [RingDuration],
    [Outcome],
    [Note],
    [Phone],
    [FromNumber],
    [ToNumber],
    [Name],
    [FirstName],
    [LastName],
    [RecordingUrl],
    [CreatedById],
    [StartedAtUtc],
    [CreatedUtc],
    [UpdatedUtc],
    [RawJson],
    [SourceSystem],
    [SourceSystemId],
    [ExtractedAtUtc]
)
SELECT
    NULLIF([CallId], '') AS [CallId],
    NULLIF([PersonId], '') AS [PersonId],
    TRY_CONVERT(INT, NULLIF([UserId], '')) AS [UserId],
    NULLIF([UserName], '') AS [UserName],
    TRY_CONVERT(BIT, NULLIF([IsIncoming], '')) AS [IsIncoming],
    TRY_CONVERT(INT, NULLIF([Duration], '')) AS [Duration],
    TRY_CONVERT(INT, NULLIF([RingDuration], '')) AS [RingDuration],
    NULLIF([Outcome], '') AS [Outcome],
    NULLIF([Note], '') AS [Note],
    NULLIF([Phone], '') AS [Phone],
    NULLIF([FromNumber], '') AS [FromNumber],
    NULLIF([ToNumber], '') AS [ToNumber],
    NULLIF([Name], '') AS [Name],
    NULLIF([FirstName], '') AS [FirstName],
    NULLIF([LastName], '') AS [LastName],
    NULLIF([RecordingUrl], '') AS [RecordingUrl],
    TRY_CONVERT(INT, NULLIF([CreatedById], '')) AS [CreatedById],
    TRY_CONVERT(DATETIME2(3), NULLIF([StartedAtUtc], '')) AS [StartedAtUtc],
    TRY_CONVERT(DATETIME2(3), NULLIF([CreatedUtc], '')) AS [CreatedUtc],
    TRY_CONVERT(DATETIME2(3), NULLIF([UpdatedUtc], '')) AS [UpdatedUtc],
    NULLIF([RawJson], '') AS [RawJson],
    NULLIF([SourceSystem], '') AS [SourceSystem],
    NULLIF([SourceSystemId], '') AS [SourceSystemId],
    TRY_CONVERT(DATETIME2(3), NULLIF([ExtractedAtUtc], '')) AS [ExtractedAtUtc]
FROM stg.Calls;
GO

-- ===== Users =====
TRUNCATE TABLE stg.Users;
GO
BULK INSERT stg.Users
FROM '$(DataDir)\Users.csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,            -- skip header (also skips the BOM line)
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0d0a',-- CRLF; if last col keeps a trailing CR, use '0x0a'
    FIELDQUOTE = '"',
    CODEPAGE = '65001',      -- UTF-8
    TABLOCK
);
GO
INSERT INTO fub.Users (
    [UserId],
    [Name],
    [FirstName],
    [LastName],
    [Email],
    [Phone],
    [Role],
    [Status],
    [Timezone],
    [IsOwner],
    [PauseLeadDistribution],
    [CanExport],
    [CanCreateApiKeys],
    [Fuid],
    [LeadEmailAddress],
    [PictureUrl],
    [GroupIds],
    [GroupNames],
    [LastSeenIosUtc],
    [LastSeenAndroidUtc],
    [LastSeenFub2Utc],
    [CreatedUtc],
    [UpdatedUtc],
    [RawJson],
    [SourceSystem],
    [SourceSystemId],
    [ExtractedAtUtc]
)
SELECT
    NULLIF([UserId], '') AS [UserId],
    NULLIF([Name], '') AS [Name],
    NULLIF([FirstName], '') AS [FirstName],
    NULLIF([LastName], '') AS [LastName],
    NULLIF([Email], '') AS [Email],
    NULLIF([Phone], '') AS [Phone],
    NULLIF([Role], '') AS [Role],
    NULLIF([Status], '') AS [Status],
    NULLIF([Timezone], '') AS [Timezone],
    TRY_CONVERT(BIT, NULLIF([IsOwner], '')) AS [IsOwner],
    TRY_CONVERT(BIT, NULLIF([PauseLeadDistribution], '')) AS [PauseLeadDistribution],
    TRY_CONVERT(BIT, NULLIF([CanExport], '')) AS [CanExport],
    TRY_CONVERT(BIT, NULLIF([CanCreateApiKeys], '')) AS [CanCreateApiKeys],
    NULLIF([Fuid], '') AS [Fuid],
    NULLIF([LeadEmailAddress], '') AS [LeadEmailAddress],
    NULLIF([PictureUrl], '') AS [PictureUrl],
    NULLIF([GroupIds], '') AS [GroupIds],
    NULLIF([GroupNames], '') AS [GroupNames],
    TRY_CONVERT(DATETIME2(3), NULLIF([LastSeenIosUtc], '')) AS [LastSeenIosUtc],
    TRY_CONVERT(DATETIME2(3), NULLIF([LastSeenAndroidUtc], '')) AS [LastSeenAndroidUtc],
    TRY_CONVERT(DATETIME2(3), NULLIF([LastSeenFub2Utc], '')) AS [LastSeenFub2Utc],
    TRY_CONVERT(DATETIME2(3), NULLIF([CreatedUtc], '')) AS [CreatedUtc],
    TRY_CONVERT(DATETIME2(3), NULLIF([UpdatedUtc], '')) AS [UpdatedUtc],
    NULLIF([RawJson], '') AS [RawJson],
    NULLIF([SourceSystem], '') AS [SourceSystem],
    NULLIF([SourceSystemId], '') AS [SourceSystemId],
    TRY_CONVERT(DATETIME2(3), NULLIF([ExtractedAtUtc], '')) AS [ExtractedAtUtc]
FROM stg.Users;
GO

-- ===== Pipelines =====
TRUNCATE TABLE stg.Pipelines;
GO
BULK INSERT stg.Pipelines
FROM '$(DataDir)\Pipelines.csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,            -- skip header (also skips the BOM line)
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0d0a',-- CRLF; if last col keeps a trailing CR, use '0x0a'
    FIELDQUOTE = '"',
    CODEPAGE = '65001',      -- UTF-8
    TABLOCK
);
GO
INSERT INTO fub.Pipelines (
    [PipelineId],
    [Name],
    [Description],
    [OrderWeight],
    [StageCount],
    [StageIds],
    [RawJson],
    [SourceSystem],
    [SourceSystemId],
    [ExtractedAtUtc]
)
SELECT
    NULLIF([PipelineId], '') AS [PipelineId],
    NULLIF([Name], '') AS [Name],
    NULLIF([Description], '') AS [Description],
    TRY_CONVERT(INT, NULLIF([OrderWeight], '')) AS [OrderWeight],
    TRY_CONVERT(INT, NULLIF([StageCount], '')) AS [StageCount],
    NULLIF([StageIds], '') AS [StageIds],
    NULLIF([RawJson], '') AS [RawJson],
    NULLIF([SourceSystem], '') AS [SourceSystem],
    NULLIF([SourceSystemId], '') AS [SourceSystemId],
    TRY_CONVERT(DATETIME2(3), NULLIF([ExtractedAtUtc], '')) AS [ExtractedAtUtc]
FROM stg.Pipelines;
GO

-- ===== Stages =====
TRUNCATE TABLE stg.Stages;
GO
BULK INSERT stg.Stages
FROM '$(DataDir)\Stages.csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,            -- skip header (also skips the BOM line)
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0d0a',-- CRLF; if last col keeps a trailing CR, use '0x0a'
    FIELDQUOTE = '"',
    CODEPAGE = '65001',      -- UTF-8
    TABLOCK
);
GO
INSERT INTO fub.Stages (
    [StageId],
    [Name],
    [PipelineId],
    [StageKind],
    [OrderWeight],
    [IsProtected],
    [PeopleCount],
    [Color],
    [ClosedStage],
    [Description],
    [RawJson],
    [SourceSystem],
    [SourceSystemId],
    [ExtractedAtUtc]
)
SELECT
    NULLIF([StageId], '') AS [StageId],
    NULLIF([Name], '') AS [Name],
    TRY_CONVERT(INT, NULLIF([PipelineId], '')) AS [PipelineId],
    NULLIF([StageKind], '') AS [StageKind],
    TRY_CONVERT(INT, NULLIF([OrderWeight], '')) AS [OrderWeight],
    TRY_CONVERT(BIT, NULLIF([IsProtected], '')) AS [IsProtected],
    TRY_CONVERT(INT, NULLIF([PeopleCount], '')) AS [PeopleCount],
    NULLIF([Color], '') AS [Color],
    TRY_CONVERT(BIT, NULLIF([ClosedStage], '')) AS [ClosedStage],
    NULLIF([Description], '') AS [Description],
    NULLIF([RawJson], '') AS [RawJson],
    NULLIF([SourceSystem], '') AS [SourceSystem],
    NULLIF([SourceSystemId], '') AS [SourceSystemId],
    TRY_CONVERT(DATETIME2(3), NULLIF([ExtractedAtUtc], '')) AS [ExtractedAtUtc]
FROM stg.Stages;
GO

-- ===== Sources =====
TRUNCATE TABLE stg.Sources;
GO
BULK INSERT stg.Sources
FROM '$(DataDir)\Sources.csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,            -- skip header (also skips the BOM line)
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0d0a',-- CRLF; if last col keeps a trailing CR, use '0x0a'
    FIELDQUOTE = '"',
    CODEPAGE = '65001',      -- UTF-8
    TABLOCK
);
GO
INSERT INTO fub.Sources (
    [SourceId],
    [Name],
    [PeopleCount],
    [Derived],
    [SourceSystem],
    [SourceSystemId],
    [ExtractedAtUtc]
)
SELECT
    TRY_CONVERT(INT, NULLIF([SourceId], '')) AS [SourceId],
    NULLIF([Name], '') AS [Name],
    TRY_CONVERT(INT, NULLIF([PeopleCount], '')) AS [PeopleCount],
    TRY_CONVERT(BIT, NULLIF([Derived], '')) AS [Derived],
    NULLIF([SourceSystem], '') AS [SourceSystem],
    NULLIF([SourceSystemId], '') AS [SourceSystemId],
    TRY_CONVERT(DATETIME2(3), NULLIF([ExtractedAtUtc], '')) AS [ExtractedAtUtc]
FROM stg.Sources;
GO

-- ===== Tags =====
TRUNCATE TABLE stg.Tags;
GO
BULK INSERT stg.Tags
FROM '$(DataDir)\Tags.csv'
WITH (
    FORMAT = 'CSV',
    FIRSTROW = 2,            -- skip header (also skips the BOM line)
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0d0a',-- CRLF; if last col keeps a trailing CR, use '0x0a'
    FIELDQUOTE = '"',
    CODEPAGE = '65001',      -- UTF-8
    TABLOCK
);
GO
INSERT INTO fub.Tags (
    [TagName],
    [PeopleCount],
    [Derived],
    [SourceSystem],
    [SourceSystemId],
    [ExtractedAtUtc]
)
SELECT
    NULLIF([TagName], '') AS [TagName],
    TRY_CONVERT(INT, NULLIF([PeopleCount], '')) AS [PeopleCount],
    TRY_CONVERT(BIT, NULLIF([Derived], '')) AS [Derived],
    NULLIF([SourceSystem], '') AS [SourceSystem],
    NULLIF([SourceSystemId], '') AS [SourceSystemId],
    TRY_CONVERT(DATETIME2(3), NULLIF([ExtractedAtUtc], '')) AS [ExtractedAtUtc]
FROM stg.Tags;
GO

-- Reconcile against data/exports/manifest.json:
SELECT 'People' AS TableName, COUNT(*) AS Rows FROM fub.People;
SELECT 'Deals' AS TableName, COUNT(*) AS Rows FROM fub.Deals;
SELECT 'Events' AS TableName, COUNT(*) AS Rows FROM fub.Events;
SELECT 'Tasks' AS TableName, COUNT(*) AS Rows FROM fub.Tasks;
SELECT 'Notes' AS TableName, COUNT(*) AS Rows FROM fub.Notes;
SELECT 'Calls' AS TableName, COUNT(*) AS Rows FROM fub.Calls;
SELECT 'Users' AS TableName, COUNT(*) AS Rows FROM fub.Users;
SELECT 'Pipelines' AS TableName, COUNT(*) AS Rows FROM fub.Pipelines;
SELECT 'Stages' AS TableName, COUNT(*) AS Rows FROM fub.Stages;
SELECT 'Sources' AS TableName, COUNT(*) AS Rows FROM fub.Sources;
SELECT 'Tags' AS TableName, COUNT(*) AS Rows FROM fub.Tags;
GO