-- Generated by scripts/generate_ddl.py — do not edit by hand.
-- Staging tables: every column NVARCHAR(MAX) so BULK INSERT never
-- fails on type. Cast happens in load_bulk_insert.sql.
IF SCHEMA_ID('stg') IS NULL EXEC('CREATE SCHEMA stg');
GO

IF OBJECT_ID('stg.People', 'U') IS NOT NULL DROP TABLE stg.People;
GO
CREATE TABLE stg.People (
    [PersonId] NVARCHAR(MAX) NULL,
    [Name] NVARCHAR(MAX) NULL,
    [FirstName] NVARCHAR(MAX) NULL,
    [LastName] NVARCHAR(MAX) NULL,
    [Stage] NVARCHAR(MAX) NULL,
    [StageId] NVARCHAR(MAX) NULL,
    [Type] NVARCHAR(MAX) NULL,
    [Source] NVARCHAR(MAX) NULL,
    [SourceId] NVARCHAR(MAX) NULL,
    [LeadFlowId] NVARCHAR(MAX) NULL,
    [AssignedUserId] NVARCHAR(MAX) NULL,
    [AssignedTo] NVARCHAR(MAX) NULL,
    [AssignedLenderId] NVARCHAR(MAX) NULL,
    [AssignedLenderName] NVARCHAR(MAX) NULL,
    [AssignedPondId] NVARCHAR(MAX) NULL,
    [PrimaryEmail] NVARCHAR(MAX) NULL,
    [PrimaryPhone] NVARCHAR(MAX) NULL,
    [Emails] NVARCHAR(MAX) NULL,
    [Phones] NVARCHAR(MAX) NULL,
    [Tags] NVARCHAR(MAX) NULL,
    [AddressStreet] NVARCHAR(MAX) NULL,
    [AddressCity] NVARCHAR(MAX) NULL,
    [AddressState] NVARCHAR(MAX) NULL,
    [AddressCode] NVARCHAR(MAX) NULL,
    [Price] NVARCHAR(MAX) NULL,
    [IsDelayed] NVARCHAR(MAX) NULL,
    [ContactedCount] NVARCHAR(MAX) NULL,
    [IsClaimed] NVARCHAR(MAX) NULL,
    [WebsiteVisits] NVARCHAR(MAX) NULL,
    [DealStatus] NVARCHAR(MAX) NULL,
    [DealStage] NVARCHAR(MAX) NULL,
    [DealName] NVARCHAR(MAX) NULL,
    [DealCloseDate] NVARCHAR(MAX) NULL,
    [DealPrice] NVARCHAR(MAX) NULL,
    [CreatedVia] NVARCHAR(MAX) NULL,
    [CreatedUtc] NVARCHAR(MAX) NULL,
    [UpdatedUtc] NVARCHAR(MAX) NULL,
    [LastActivityUtc] NVARCHAR(MAX) NULL,
    [CustomBirthday] NVARCHAR(MAX) NULL,
    [CustomClosingAnniversary] NVARCHAR(MAX) NULL,
    [CustomColdCaller] NVARCHAR(MAX) NULL,
    [CustomDateOfSale] NVARCHAR(MAX) NULL,
    [CustomEstimatedAvailableEquity] NVARCHAR(MAX) NULL,
    [CustomEstimatedEquity] NVARCHAR(MAX) NULL,
    [CustomEstimatedLoanBalance] NVARCHAR(MAX) NULL,
    [CustomHomeownerDeceased] NVARCHAR(MAX) NULL,
    [CustomInterestRate] NVARCHAR(MAX) NULL,
    [CustomLTVRatio] NVARCHAR(MAX) NULL,
    [CustomLease] NVARCHAR(MAX) NULL,
    [CustomLeaseExpiry] NVARCHAR(MAX) NULL,
    [CustomLengthOfOwnership] NVARCHAR(MAX) NULL,
    [CustomMonthlyRent] NVARCHAR(MAX) NULL,
    [CustomMortgageAmount] NVARCHAR(MAX) NULL,
    [CustomMortgagee] NVARCHAR(MAX) NULL,
    [CustomOccupancy] NVARCHAR(MAX) NULL,
    [CustomPropertiesAtMailingAddress] NVARCHAR(MAX) NULL,
    [CustomPropertyCondition] NVARCHAR(MAX) NULL,
    [CustomSRan] NVARCHAR(MAX) NULL,
    [CustomSellerSIdealPrice] NVARCHAR(MAX) NULL,
    [CustomWebsite] NVARCHAR(MAX) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [SourceSystem] NVARCHAR(MAX) NULL,
    [SourceSystemId] NVARCHAR(MAX) NULL,
    [ExtractedAtUtc] NVARCHAR(MAX) NULL
);
GO

IF OBJECT_ID('stg.Deals', 'U') IS NOT NULL DROP TABLE stg.Deals;
GO
CREATE TABLE stg.Deals (
    [DealId] NVARCHAR(MAX) NULL,
    [Name] NVARCHAR(MAX) NULL,
    [DealType] NVARCHAR(MAX) NULL,
    [Status] NVARCHAR(MAX) NULL,
    [Price] NVARCHAR(MAX) NULL,
    [OrderWeight] NVARCHAR(MAX) NULL,
    [Description] NVARCHAR(MAX) NULL,
    [PipelineId] NVARCHAR(MAX) NULL,
    [PipelineName] NVARCHAR(MAX) NULL,
    [StageId] NVARCHAR(MAX) NULL,
    [StageName] NVARCHAR(MAX) NULL,
    [EnteredStageUtc] NVARCHAR(MAX) NULL,
    [CommissionValue] NVARCHAR(MAX) NULL,
    [AgentCommission] NVARCHAR(MAX) NULL,
    [TeamCommission] NVARCHAR(MAX) NULL,
    [TimeToClose] NVARCHAR(MAX) NULL,
    [ProjectedCloseDate] NVARCHAR(MAX) NULL,
    [EarnestMoneyDueDate] NVARCHAR(MAX) NULL,
    [MutualAcceptanceDate] NVARCHAR(MAX) NULL,
    [DueDiligenceDate] NVARCHAR(MAX) NULL,
    [FinalWalkThroughDate] NVARCHAR(MAX) NULL,
    [PossessionDate] NVARCHAR(MAX) NULL,
    [CustomClosingDate] NVARCHAR(MAX) NULL,
    [PrimaryPersonId] NVARCHAR(MAX) NULL,
    [PersonIds] NVARCHAR(MAX) NULL,
    [PersonNames] NVARCHAR(MAX) NULL,
    [PrimaryUserId] NVARCHAR(MAX) NULL,
    [UserIds] NVARCHAR(MAX) NULL,
    [UserNames] NVARCHAR(MAX) NULL,
    [CreatedUtc] NVARCHAR(MAX) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [SourceSystem] NVARCHAR(MAX) NULL,
    [SourceSystemId] NVARCHAR(MAX) NULL,
    [ExtractedAtUtc] NVARCHAR(MAX) NULL
);
GO

IF OBJECT_ID('stg.Events', 'U') IS NOT NULL DROP TABLE stg.Events;
GO
CREATE TABLE stg.Events (
    [EventId] NVARCHAR(MAX) NULL,
    [PersonId] NVARCHAR(MAX) NULL,
    [Type] NVARCHAR(MAX) NULL,
    [Source] NVARCHAR(MAX) NULL,
    [Message] NVARCHAR(MAX) NULL,
    [Description] NVARCHAR(MAX) NULL,
    [NoteId] NVARCHAR(MAX) NULL,
    [PageTitle] NVARCHAR(MAX) NULL,
    [PageUrl] NVARCHAR(MAX) NULL,
    [PageDuration] NVARCHAR(MAX) NULL,
    [Property] NVARCHAR(MAX) NULL,
    [PropertySearch] NVARCHAR(MAX) NULL,
    [Additional] NVARCHAR(MAX) NULL,
    [OccurredUtc] NVARCHAR(MAX) NULL,
    [CreatedUtc] NVARCHAR(MAX) NULL,
    [UpdatedUtc] NVARCHAR(MAX) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [SourceSystem] NVARCHAR(MAX) NULL,
    [SourceSystemId] NVARCHAR(MAX) NULL,
    [ExtractedAtUtc] NVARCHAR(MAX) NULL
);
GO

IF OBJECT_ID('stg.Users', 'U') IS NOT NULL DROP TABLE stg.Users;
GO
CREATE TABLE stg.Users (
    [UserId] NVARCHAR(MAX) NULL,
    [Name] NVARCHAR(MAX) NULL,
    [FirstName] NVARCHAR(MAX) NULL,
    [LastName] NVARCHAR(MAX) NULL,
    [Email] NVARCHAR(MAX) NULL,
    [Phone] NVARCHAR(MAX) NULL,
    [Role] NVARCHAR(MAX) NULL,
    [Status] NVARCHAR(MAX) NULL,
    [Timezone] NVARCHAR(MAX) NULL,
    [IsOwner] NVARCHAR(MAX) NULL,
    [PauseLeadDistribution] NVARCHAR(MAX) NULL,
    [CanExport] NVARCHAR(MAX) NULL,
    [CanCreateApiKeys] NVARCHAR(MAX) NULL,
    [Fuid] NVARCHAR(MAX) NULL,
    [LeadEmailAddress] NVARCHAR(MAX) NULL,
    [PictureUrl] NVARCHAR(MAX) NULL,
    [GroupIds] NVARCHAR(MAX) NULL,
    [GroupNames] NVARCHAR(MAX) NULL,
    [LastSeenIosUtc] NVARCHAR(MAX) NULL,
    [LastSeenAndroidUtc] NVARCHAR(MAX) NULL,
    [LastSeenFub2Utc] NVARCHAR(MAX) NULL,
    [CreatedUtc] NVARCHAR(MAX) NULL,
    [UpdatedUtc] NVARCHAR(MAX) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [SourceSystem] NVARCHAR(MAX) NULL,
    [SourceSystemId] NVARCHAR(MAX) NULL,
    [ExtractedAtUtc] NVARCHAR(MAX) NULL
);
GO

IF OBJECT_ID('stg.Pipelines', 'U') IS NOT NULL DROP TABLE stg.Pipelines;
GO
CREATE TABLE stg.Pipelines (
    [PipelineId] NVARCHAR(MAX) NULL,
    [Name] NVARCHAR(MAX) NULL,
    [Description] NVARCHAR(MAX) NULL,
    [OrderWeight] NVARCHAR(MAX) NULL,
    [StageCount] NVARCHAR(MAX) NULL,
    [StageIds] NVARCHAR(MAX) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [SourceSystem] NVARCHAR(MAX) NULL,
    [SourceSystemId] NVARCHAR(MAX) NULL,
    [ExtractedAtUtc] NVARCHAR(MAX) NULL
);
GO

IF OBJECT_ID('stg.Stages', 'U') IS NOT NULL DROP TABLE stg.Stages;
GO
CREATE TABLE stg.Stages (
    [StageId] NVARCHAR(MAX) NULL,
    [Name] NVARCHAR(MAX) NULL,
    [PipelineId] NVARCHAR(MAX) NULL,
    [StageKind] NVARCHAR(MAX) NULL,
    [OrderWeight] NVARCHAR(MAX) NULL,
    [IsProtected] NVARCHAR(MAX) NULL,
    [PeopleCount] NVARCHAR(MAX) NULL,
    [Color] NVARCHAR(MAX) NULL,
    [ClosedStage] NVARCHAR(MAX) NULL,
    [Description] NVARCHAR(MAX) NULL,
    [RawJson] NVARCHAR(MAX) NULL,
    [SourceSystem] NVARCHAR(MAX) NULL,
    [SourceSystemId] NVARCHAR(MAX) NULL,
    [ExtractedAtUtc] NVARCHAR(MAX) NULL
);
GO

IF OBJECT_ID('stg.Sources', 'U') IS NOT NULL DROP TABLE stg.Sources;
GO
CREATE TABLE stg.Sources (
    [SourceId] NVARCHAR(MAX) NULL,
    [Name] NVARCHAR(MAX) NULL,
    [PeopleCount] NVARCHAR(MAX) NULL,
    [Derived] NVARCHAR(MAX) NULL,
    [SourceSystem] NVARCHAR(MAX) NULL,
    [SourceSystemId] NVARCHAR(MAX) NULL,
    [ExtractedAtUtc] NVARCHAR(MAX) NULL
);
GO

IF OBJECT_ID('stg.Tags', 'U') IS NOT NULL DROP TABLE stg.Tags;
GO
CREATE TABLE stg.Tags (
    [TagName] NVARCHAR(MAX) NULL,
    [PeopleCount] NVARCHAR(MAX) NULL,
    [Derived] NVARCHAR(MAX) NULL,
    [SourceSystem] NVARCHAR(MAX) NULL,
    [SourceSystemId] NVARCHAR(MAX) NULL,
    [ExtractedAtUtc] NVARCHAR(MAX) NULL
);
GO
